web-platform-tests/wpt-pr-bot

- lib/metadata/index.js
See https://github.com/w3c/web-platform-tests/pull/8986 for some background.
Starting with @fwang @rniwa and myself for downstream reviews of WPT PRs.
CCing @foolip as well.
Not exactly sure whether WebKit export script puts "WebKit export" inside "content" (PR title starts with WebKit export). It should be fairly easy anyway to adapt WebKit export script if need be.
> Adding reviewer exemption for some WebKit exports

- lib/github.js
- lib/test-urls-comment.js
This needs to be merged post wpt migration to ensure reviewers are still notified of new pull requests.
> wpt migration: update GitHub repo and org names

- lib/github.js
This is towards #41. The intention is to use the [Update a reference](https://developer.github.com/v3/git/refs/#update-a-reference) GitHub API to update branches triggered by the wpt.fyi revision announcer (see web-platform-tests/wpt.fyi#551 for tracking announcer changes towards this).
> Add PATCH method to github API lib

- package.json
Node.js version 4 reached end-of-life on April 2018 [1]. Update to
version 8, the latest LTS relase, due to receive support until December
2019.
[1] https://github.com/nodejs/Release/tree/19985fe7c16c764805bed84ea4901488bec35cbf#release-schedule
---
Note that merging this patch will trigger re-deployment. Test coverage isn't great in this project, so maintainers should actively monitor performance following the merge.
> Deploy to Node.js version 8

- index.js
- lib/epochs.js
This introduces a new `/update-epoch` endpoint that updates the `epochs/[epoch]` branch ref in `web-platform-tests/wpt` iff it has changed.
The request format expected from the wpt.fyi revision announcer is verified, but no authentication is required; the revision announcer API (rather than the incoming request body) is trusted to deliver an accurate epochal hash.
This is towards #41 and web-platform-tests/wpt.fyi#551.
CC @foolip
> Implement epochal update hook

- lib/metadata/choose-assignee.js
- test/get-metadata.js
For the ~500 or so already-existing PRs, a random assignee isn't a great pick.
This changes the assignment to check for existing reviews, and assigns the most recent reviewer if there are any.
> Assign the last reviewer if applicable

- index.js
After https://github.com/web-platform-tests/wpt/issues/14836,
Safari Technology Preview runs are completing in ~1.5h. This makes it feasible
to run more frequently, so sync the 12- and 6-hour epoch branches too.
> Also update epochs/twelve_hourly and epochs/six_hourly branches

- index.js
GitHub recently added support for "draft" pull requests, and this
project subsequently began ignoring them upon creation [2]. Complete the
implementation of that change by recognizing when "drafts" move to a
"ready" state and acting on the pull request.
[1] https://github.blog/2019-02-14-introducing-draft-pull-requests/
[2] cd003b22152c06661949292f06270026b78e59d3
> React when draft pull requests are marked "ready"

- package.json
Avoids this warning from `npm install`:
> npm WARN wpt-pr-bot@0.4.0 No repository field.
> Add the `repository` field to package.json

- lib/comment.js
- lib/metadata/index.js
- test/get-metadata.js
Some downstream projects create a pull request before code review has
been completed [1]. Update the generated comment to avoid suggesting
otherwise, and extend with the name of the downstream project where
review is under way.
[1] https://github.com/servo/servo/pull/22809#issuecomment-459963112
> Improve comment describing downstream review

- index.js
- lib/filter.js
- test/filter.js
This is not plain refactoring, as the `state == "closed"` condition
replaces the check on `merged`. It also ensures that we perform the
same checks both on the event payload and on the response from
https://developer.github.com/v3/pulls/#get-a-single-pull-request.
Fixes https://github.com/web-platform-tests/wpt-pr-bot/issues/38.
Fixes https://github.com/web-platform-tests/wpt-pr-bot/issues/69.
> Extract event and pull request filtering and attempt to make robust

- .gitignore
- package-lock.json
This will cause Travis CI to use `npm ci`:
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#npm-ci-support
The reason for doing this is to pin transient dependencies as well.
> Put package-lock.json under version control

- lib/metadata/labels.js
There could be other things in .github/, but currently there isn't,
and matching everything avoid the .github label being recreated if
.github/META.yml is touched.
Like https://github.com/web-platform-tests/wpt-pr-bot/pull/64.
> Automatically label GitHub Actions PRs

- package-lock.json
- package.json
It is only `require()`'d in test/get-metadata.js.
This reduces the number of packages installed by
`npm install --production` from 121 to 105.
> Move sinon from `dependencies` to `devDependencies`

- lib/filter.js
- test/filter.js
This field can currently be observed here:
https://api.github.com/repos/web-platform-tests/wpt/pulls/19806
There's no stability guarantee here, it's a quickfix.
Fixes https://github.com/web-platform-tests/wpt-pr-bot/issues/69.
> Also check `mergeable_state` to identify draft pull requests

- lib/metadata/labels.js
- test/labels.js
This is not a likely case, but it's also not something that should crash the script.
> Tolerate pull requests that modify zero files

- package-lock.json
- package.json
It was introduced with commit b6fdf12f687b7c54a8469cfc3b21127253cb1404
for email notifications and later not removed with that feature in
commit d09a9d10a4c0dd923c0a89aae6263109e06cace7.
> Remove unused dependency ent

- .github/workflows/test.yml
- .travis.yml
This is mostly to make the `npm test` explicit and make it easier
to add more jobs or steps. Also aligns with the wpt repo.
> Migrate testing to GitHub Actions

- .github/workflows/test.yml
The deployment is still using 8, but 12 is now LTS and the version
we'd likely upgrade to, making it the more useful version to test.
> Run tests on Node.js 8+12 instead of 8+10

- .gcloudignore
- .gitignore
- app.yaml
- create-secrets.js
- index.js
- lib/comment.js
- lib/github.js
- lib/label-model.js
- package-lock.json
- package.json
This essentially cherry-picks 3 changes from the appengine branch into master (see https://github.com/web-platform-tests/wpt-pr-bot/issues/128):
1. Add a dry-run mode (but don't run in it)
1. Add deployment info for appengine
1. Add ability to pick up secrets downloaded from the datastore, if they exist
After this change, the diff between appengine and master would be: 
[unported_diff.txt](https://github.com/web-platform-tests/wpt-pr-bot/files/3946470/unported_diff.txt)
> Bring most appengine changes into master

- index.js
Currently the code is hard-coded to run in dry-run mode, until we've
proved out that it should do what we expect.
Also reduces the frequency from every minute to every 5 minutes, since
we will be doing the same thing over-and-over (since we're in dry-run
mode and so nothing will actually change).
> Enable (dry-run guarded) code to comment/label WebKit exports

- index.js
- lib/metadata/index.js
This removes the hard-coded dryRun flag for labelling and approving
WebKit-exported PRs, and uses the normal dry-run support instead.
Effectively, this launches the feature (since prod doesn't run in
dry-run mode!).
The 5-minute interval is left in place; I plan to remove it when we're
confident that the bot is doing the right thing.
> Ship the webkit-export support

- index.js
- lib/bugs-webkit.js
- lib/comment.js
- lib/filter.js
- lib/github.js
- lib/label-model.js
- lib/logger.js
- package-lock.json
- package.json
This uses the bunyan logging framework to produce logs that will be
easier to read when using GCP, as it will group them by request and
separate metadata (such as level information) from the message contents.
> Add GCP logging integration using bunyan

- .github/dependabot.yml
- renovate.json
We use Dependabot for most other repos in web-platform-tests.
> Switch from Renovate to Dependabot

- .github/workflows/test.yml
We don't do anything special so it's unlikely an upgrade of
ubuntu-latest will break tests. On the other hand, ubuntu-18.04 is
certain to be retired at some point, which would break us.
> Run GitHub Actions on latest Ubuntu

- index.js
Taking the value of logger.info and later trying to invoke it doesn't
work, and results in the error "attempt to log with an unbound log
method" in GCP logs.
> Fix unbound logger.info

- lib/logger.js
This is to avoid unconditionally trying to use
@google-cloud/logging-bunyan, which results in a "Unable to detect a
Project Id in the current environment" error while running tests.
> Make logging depend on the environment

- package-lock.json
- package.json
js-yaml, minimatch and node-fetch are not upgraded to their latest major
releases as they all break tests in one way or another.
> Bump dependencies as much as possible

- create-secrets.js
- index.js
- package-lock.json
- package.json
Fixes #213
Code changes:
- Repurpose create-secrets.js to read secrets on startup from secret manager. Previously, the secrets were bundled in the package uploaded to app engine. That means anyone downloading the bundle would get the secrets.
- Because loadSecrets is now async, add promise chaining to index.js so that the secrets are loaded first before the app starts to prevent race conditions. Added some parts into functions to make main() more readable. The code moved into functions is unchanged
> Use Google Cloud Secret Manager to fill in secrets

- .github/workflows/test.yml
- README.md
- app.yaml
This version will be supported by GCP until 2025-04-30: https://cloud.google.com/appengine/docs/standard/lifecycle/support-schedule#nodejs Also clean up the README.md file since #213 was merged.
> Upgrade to Node.js 18

- lib/metadata/find-owners.js
- lib/metadata/index.js
- test/find-owners.js
- test/get-metadata.js
Fixes https://github.com/web-platform-tests/wpt-pr-bot/issues/253.
> Route WEB_FEATURES.yml changes to web-features contributors

- package-lock.json
- package.json
This is the latest version to not require ESM, which we can't upgrade to:
https://github.com/web-platform-tests/wpt-pr-bot/pull/249
> Bump chai from 4.3.6 to 4.4.1
